require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'Summer' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNDateTimePicker', :path => '../node_modules/@react-native-community/datetimepicker'

  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-async-storage/async-storage'

  pod 'react-native-maps', :path => '../node_modules/react-native-maps'

  pod 'react-native-geolocation', :path => '../node_modules/@react-native-community/geolocation'

  pod 'react-native-geolocation-service', :path => '../node_modules/react-native-geolocation-service'

  target 'SummerTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'Summer-tvOS' do
  # Pods for Summer-tvOS

  target 'Summer-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
